version: '3.8'

services:
  web:
    build: ./project
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./project/:/usr/src/app
    ports:
      - 5001:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine3.15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user_1
      - POSTGRES_PASSWORD=password_1
      - POSTGRES_DB=logger_db

volumes:
  postgres_data:
    name: postgres_data
